### ISSUE TITLE
fix: invalid JSON in `examples/data-rights/example.json`

### ISSUE THREAD

**Issue by jgeluk** [EKGF/dprod#110]
See https://github.com/EKGF/dprod/blame/a78e2f110d9ec729fbe6f74317db3b379cfade56/examples/data-rights/example.json#L5.

Doesn't look like valid JSON.

Neither does ```"rightOperand": [region:EMEA, region:APAC]``` in the same file.

**Comment by jgeluk** [comment]
@joshcornejo ?

**Comment by joshcornejo** [comment]
I only changed the areas that were the reported problem.

All fixed now.

**Comment by rivettp** [comment]
Here is the link to the OMG FTF issue https://issues.omg.org/browse/DPROD-8
