### ISSUE TITLE
ontologies, shapes and diagrams discrepancies

### ISSUE THREAD

**Issue by joshcornejo** [EKGF/dprod#73]
Diagram & this link https://github.com/EKGF/data-product-spec/blob/main/dprod.ttl

Both include `dprod:productionProcessDescription`.

Neither of the more recent  ttl files at https://github.com/EKGF/dprod/tree/main/ontology/dprod do have this property.

**Comment by andrea-gioia** [comment]
We will remove the property in the new version of the diagram. We can marge this issue with issue #73

**Comment by andrea-gioia** [comment]
This issue has been merged with issue #94

**Comment by rivettp** [comment]
Here is the OMG FTF issue https://issues.omg.org/browse/DPROD-1
