### ISSUE TITLE
Check domain and range hyperlinks to DCAT in specification

### ISSUE THREAD

**Issue by ericstephan** [EKGF/dprod#78]
Some domain and range hyperlinks redirect browsers to the DCAT 2 specification.

For example:  https://ekgf.github.io/dprod/#inputdataset .  If you click on the Range link it takes you back to DCAT 2 . 

Best regards,

Eric Stephan
Pacific Northwest National Laboratory

**Comment by rivettp** [comment]
That is really an issue for DCAT since they decided to use the same namespace for DCAT 2 as was used for DCAT 3. We'll try to take it up with them.

**Comment by rivettp** [comment]
FYI the DCAT team is taking action https://github.com/w3c/dxwg/pull/1618

**Comment by rivettp** [comment]
It has been fixed in DCAT now. https://github.com/w3c/dxwg/pull/1618. This required no change in DPROD. 
Here is the issue in OMG FTF https://issues.omg.org/browse/DPROD-13
