### ISSUE TITLE
rename JSONLD files to `.jsonld`

### ISSUE THREAD

**Issue by VladimirAlexiev** [EKGF/dprod#89]
https://github.com/EKGF/dprod/blob/main/examples/data-quality/example.json is a JSON-LD file. 
Rename it to `.jsonld` so I can invoke
```
riot -out=trig example.jsonld
```
without having to specify the input syntax:
```
riot -out=trig -syntax=jsonld example.json
```

**Comment by rivettp** [comment]
I agree, this is more common and makes sense.

**Comment by rivettp** [comment]
Here is the OMG FTF issue https://issues.omg.org/browse/DPROD-7
